### ISSUE TITLE
getAccountsByType always return a new Account[]

### ISSUE THREAD

**Issue by jzeferino** [massivedisaster/ADAL#132]
@Andrer757 has reported a problem with accounts that seem to happen when calling `getCurrentAccount`.

`getCurrentAccount` return a new instance of  `Account[]` for each call. This behavior leads to problems when getting the account.

The use case:

Calling `hasAccount` return `true`.
Calling `getAccount` result in `Exception`.

Fixed in #131

**Comment by extmkv** [comment]
@jzeferino Can we close this issue?

**Comment by jzeferino** [comment]
@extmkv I didn't close it because we need to document this behavior somewhere. Can't find the right place.
