### ISSUE TITLE
Android 8.0 permissions in accounts

### ISSUE THREAD

**Issue by jzeferino** [massivedisaster/ADAL#134]
source: https://android-developers.googleblog.com/2017/12/improving-app-security-and-performance.html

**Comment by jzeferino** [comment]
@Andrer757 can you tell me if we really will need this?

**Comment by extmkv** [comment]
I've been checking the changes from android 8.0 and this paragraph are very interesting:

> In Android 8.0 (API level 26), apps can no longer get access to user accounts unless the authenticator owns the accounts or the user grants that access.

Ok I think is a no problem, we only access to user accounts from our authenticator.

> The GET_ACCOUNTS permission is no longer sufficient. To be granted access to an account, apps should either use AccountManager.newChooseAccountIntent() or an authenticator-specific method. After getting access to accounts, an app can can call AccountManager.getAccounts() to access them. 

Need to be verified we must continue to use the permission GET_ACCOUNTS our not.

Source: https://developer.android.com/about/versions/oreo/android-8.0-changes.html#aaad

**Comment by jzeferino** [comment]
@extmkv As said in the link I pasted above:

> Many of these changes only apply to apps that explicitly declare their support for new API behaviors, through the targetSdkVersion manifest attribute. For example, only apps with a targetSdkVersion of 23 (the API level of Android 6.0) or higher give the user full control over what private data – such as contacts or location – the app can access via runtime permissions. Similarly, recent releases include user experience improvements that prevent apps from accidentally overusing resources like battery and memory; background execution limits is a good example of this type of improvement.
> 
> In order to provide users with the best Android experience possible, the Google Play Console will require that apps target a recent API level:
> 
> August 2018: New apps required to target API level 26 (Android 8.0) or higher.
> November 2018: Updates to existing apps required to target API level 26 or higher.
> 2019 onwards: Each year the targetSdkVersion requirement will advance. Within one year following each Android dessert release, new apps and app updates will need to target the corresponding API level or higher.
>

**Comment by extmkv** [comment]
> @extmkv As said in the link I pasted above:
> 
>     Many of these changes only apply to apps that explicitly declare their support for new API behaviors, through the targetSdkVersion manifest attribute. For example, only apps with a targetSdkVersion of 23 (the API level of Android 6.0) or higher give the user full control over what private data – such as contacts or location – the app can access via runtime permissions. Similarly, recent releases include user experience improvements that prevent apps from accidentally overusing resources like battery and memory; background execution limits is a good example of this type of improvement.
> 
>     In order to provide users with the best Android experience possible, the Google Play Console will require that apps target a recent API level:
> 
>     August 2018: New apps required to target API level 26 (Android 8.0) or higher.
>     November 2018: Updates to existing apps required to target API level 26 or higher.
>     2019 onwards: Each year the targetSdkVersion requirement will advance. Within one year following each Android dessert release, new apps and app updates will need to target the corresponding API level or higher.

@jzeferino I don't see anything related with the accounts there.

**Comment by jzeferino** [comment]
@extmkv the only directly account related statement is:

> Target API level requirement from late 2018
> 
> API behavior changes advance the security and privacy protections of Android – helping developers secure their apps and protecting people from malware. Here are a few such changes from recent platform versions:
> 
> Implicit intents for bindService() no longer supported (Android 5.0)
> Runtime permissions (Android 6.0)
> User-added CAs not trusted by default for secure connections (Android 7.0)
> **Apps can't access user accounts without explicit user approval (Android 8.0)**
> Many of these changes only apply to apps that explicitly declare their support for new API behaviors, through the targetSdkVersion manifest attribute. For example, only apps with a targetSdkVersion of 23 (the API level of Android 6.0) or higher give the user full control over what private data – such as contacts or location – the app can access via runtime permissions. Similarly, recent releases include user experience improvements that prevent apps from accidentally overusing resources like battery and memory; background execution limits is a good example of this type of improvement.

**Comment by jorge-costa-carbon** [comment]
As I said in the first comment: In Android 8.0 (API level 26), apps can no longer get access to user accounts *unless the authenticator owns the accounts* or the user grants that acc...

**Comment by jzeferino** [comment]
We're playing ping pong here.
I've created this issue to highlight that we could have some problems in the future regarding Android 8 as said in the google blog post.

I can't say if this will be a problem or not yet.
