### ISSUE TITLE
Add license header to every file

### ISSUE THREAD

**Issue by jzeferino** [massivedisaster/ADAL#23]
I've a pending commit witch adds a license header to **every file**.

The header looks like:

> ADAL - A set of Android libraries to help speed up Android development.
> Copyright (C) 2017 ADAL.
> 
> ADAL is free software; you can redistribute it and/or modify it under
> the terms of the GNU Lesser General Public License as published by the Free
> Software Foundation; either version 3 of the License, or any later version.
>  
> ADAL is distributed in the hope that it will be useful, but WITHOUT
> ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
> FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
> details.
> 
> You should have received a copy of the GNU Lesser General Public License along
> with ADAL. If not, see <http://www.gnu.org/licenses/>.

* This will imply that _EVERY_ developer should configure the header for this project in Android Studio (I also have done this, with some screenshots.)
* We could check for this headers being added when some one PR's.

After understanding this implications, what do you think? Should we proceed or leave it without any headers?

**Comment by jzeferino** [comment]
@extmkv need your opinion on that.

**Comment by extmkv** [comment]
@jzeferino Ok, do it
