### ISSUE TITLE
Add building and uploading artifacts to jfrog

### ISSUE THREAD

**Issue by jzeferino** [massivedisaster/ADAL#5]
Add documentation in readme/wiki on how to build, deploy and distribute artifacts to jfrog.

**Comment by jzeferino** [comment]
@extmkv I'm resurrecting this because ATM only you have the knowledge/credentials to publish new versions. Can you update me on this?

**Comment by extmkv** [comment]
yes of course, I will create a new entry in Wiki with that information.
