### ISSUE TITLE
Add modules to JCenter

### ISSUE THREAD

**Issue by extmkv** [massivedisaster/ADAL#52]
The packages were transferred to the organization in bintray and the link with JCenter was lost, so
I sent a message to JFrog support to help us with the issue.

**Comment by extmkv** [comment]
I have deleted all packages in my private account and request to link the package in the organization with the JCenter.

**Comment by jzeferino** [comment]
How are we? @extmkv

**Comment by extmkv** [comment]
@jzeferino Last night JFrog sends me an email about that. They are working on it.

**Comment by jzeferino** [comment]
We're good on this.
