### ISSUE TITLE
Add more samples and use cases in sample project

### ISSUE THREAD

**Issue by jzeferino** [massivedisaster/ADAL#6]
Add more samples and use cases in sample project

**Comment by jzeferino** [comment]
Added samples for:

[65bf4b8] for bangbus.
[8ce0929] for accounts.

**Comment by jzeferino** [comment]
@extmkv hope you can review how we are on this.

**Comment by extmkv** [comment]
Added sample for:
- Analytics
- Adapter
- Network
- Utils
