### ISSUE TITLE
Add individual documentation for each module.

### ISSUE THREAD

**Issue by jzeferino** [massivedisaster/ADAL#91]
I was thinking in, adding documentation and GIF for every module.
That documentation could be done individually for each module.

I suggest something like a table in the readme that points for the specific module documentation inside a docs folder.

What do you guys think? @massivedisaster/adal-team

**Comment by jzeferino** [comment]
Here's the list of the current modules.

- [x]  adal-accounts (jzeferino)	
- [x]  adal-adapters (extmkv)
- [x]  adal-alarm (extmkv)
- [x]  adal-analytics (jzeferino)
- [x]  adal-application-state (jzeferino)
- [x]  adal-bus (luisvitela)	
- [x]  adal-fragments (extmkv)
- [x]  adal-location (jzeferino)
- [x]  adal-network (jzeferino)	
- [x]  adal-permissions (jzeferino)	
- [x]  adal-utils (luisvitela)

**Comment by extmkv** [comment]
Sounds good

**Comment by luisvitela** [comment]
@Here's the list of missing steps

- [x]  adal-application-state (gif) (@jzeferino)	
- [x]  adal-accounts (gif) (@jzeferino)
- [x]  adal-alarm ([gif](https://im2.ezgif.com/tmp/ezgif-2-90a1091b69.gif)) (@luisvitela)
- [x]  adal-adapters (description, [gif)](https://im2.ezgif.com/tmp/ezgif-2-00b1c8e5b9.gif) (@extmkv)
- [x]  adal-fragments (missing AbstractRequestFragment) (@extmkv)
- [x]  adal-network (description, [gif](https://im2.ezgif.com/tmp/ezgif-2-103c3b92b4.gif)) (@Andrer757)

**Comment by extmkv** [comment]
Please @jzeferino and @luisvitela check if is everything ok

**Comment by jzeferino** [comment]
@extmkv  it LGTM, can I PR it @luisvitela?

**Comment by luisvitela** [comment]
of course @jzeferino
