### ISSUE TITLE
Add graddle task to update readmes

### ISSUE THREAD

**Issue by jzeferino** [massivedisaster/ADAL#95]
The readme update was made by deploy automator, witch is a responsibility that should't be there.
Moving this logic from deploy automator forces us to put that logic somewhere.

1. A gradle task could be a option but if we do that we can't re-use that code (only by copy).
2. Another tool, will be overkill, IMO, because then we will have to run 2 tools when releasing a version.

What do you guys think?
@massivedisaster/adal-team

**Comment by extmkv** [comment]
The first one. 
We can make a task for the project and then call the task in every module passing the file by parameter.

**Comment by jzeferino** [comment]
@extmkv I've already have a implementation for the first one approach. It searches SemanticVersion in every .md file and mass replace it.
I could have instead a list of files or a pattern to search.

The problem of this approach is that we would have a task like (a copy) this for other projects (like AFM).
